encoding: utf-8
baseurl: /BIO181G_Fall18
url: SchwartzLabURI.github.io/BIO181G_Fall18/
permalink: /:title/
disqus_shortname: BIO181G Fall 2018
prose:
  media: /img
  ignore:
    - /_includes
    - /_layouts
    - /_sass
    - /fonts
    - /js
  metadata:
    _posts/weeks:
      - name: "layout"
        field:
          element: "hidden"
          value: "course_page"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "category"
        field:
          element: "hidden"
          value: "content"
    _posts/info:
      - name: "layout"
        field:
          element: "hidden"
          value: "info"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "category"
        field:
          element: "hidden"
          value: "info"
